// client/src/AiBadge.jsx
// Shared component — renders wherever AI-generated content appears

const SPARKLES_PATH = "M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0L9.937 15.5z";

// Inline sparkle SVG
export const SparkleIcon = ({ size = 12, color = "#7048E8" }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none"
    stroke={color} strokeWidth={1.8} strokeLinecap="round" strokeLinejoin="round">
    <path d={SPARKLES_PATH}/>
  </svg>
);

// Compact inline badge — use inside text/list rows
// variant: "badge" | "inline" | "dot"
export default function AiBadge({ label = "AI", variant = "badge", tooltip = "Generated by AI" }) {
  const purple = "#7048E8";
  const styles = {
    badge: {
      display: "inline-flex", alignItems: "center", gap: 3,
      padding: "1px 6px", borderRadius: 5,
      background: `${purple}12`, border: `1px solid ${purple}25`,
      fontSize: 10, fontWeight: 700, color: purple,
      whiteSpace: "nowrap", flexShrink: 0,
      fontFamily: "'DM Sans', -apple-system, sans-serif",
    },
    inline: {
      display: "inline-flex", alignItems: "center", gap: 3,
      fontSize: 11, fontWeight: 600, color: purple,
      whiteSpace: "nowrap",
    },
    dot: {
      display: "inline-flex", alignItems: "center", justifyContent: "center",
      width: 16, height: 16, borderRadius: "50%",
      background: `${purple}15`, flexShrink: 0,
    },
  };

  return (
    <span title={tooltip} style={styles[variant] || styles.badge}>
      <SparkleIcon size={variant === "dot" ? 9 : 9} color={purple}/>
      {variant !== "dot" && label}
    </span>
  );
}

// Helper — returns true if a note/comm was AI-generated
export function isAiGenerated(item) {
  if (!item) return false;
  const author = (item.author || item.created_by || item.sent_by || "").toLowerCase();
  return author.includes("agent") || author.includes("ai") ||
    item.ai_generated === true || item.status === "draft" && author.includes("agent");
}
